site_name: ML Engineer's Blog
site_description: |
  Portfolio and blog about Artificial Intelligence and Machine Learning
site_author: Sebastien Tadiello
edit_uri: ""
copyright: Copyright Â© 2024 Sebastien Tadiello

theme:
  name: material
  # custom_dir: overrides
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    scheme: slate
    primary: black
    accent: light green
    # '00ff00' '#229954'

extra:
  social:
    # - icon: hf
    #   link: https://huggingface.co/sebDtSci
    # - icon: fontawesome/brands/square-x-twitter
    #   link: https://twitter.com/SbastienT10
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sebastien-t-ababa2128/
    - icon: fontawesome/brands/github
      link: https://github.com/sebDtSci
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?view_op=list_works&hl=fr&user=EkjvvMIAAAAJ

extra_css:
    - 'extra1.css'
extra_javascript:
  # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
      preview: true
  - pymdownx.details

plugins:
  - search
  - blog

  - awesome-pages
  - git-revision-date-localized
  # - mkdocs-minify-plugin
  # - meta

docs_dir: docs

nav:
  - Home: index.md
  # - Portfolio:
  #     - Open Source Projects: portfolio/open-source.md
  #     - Past Contributions: portfolio/open-source-history.md
  #     - About me:
  #         - Biography: portfolio/biography.md
  - Blog:
      - blog/index.md
  - Basics:
      - basics/index.md
      - Mathematics: 
        - basics/maths/index.md
        - basics/maths/base2.md
      - Python:
        - basics/python/numpy.md
  - Projets:
      - projets/index.md
  # - Phylosophy: phylosophy.md